language: node_js
node_js:
  - "0.10.33"
services:
  - mongodb
env: CODECLIMATE_REPO_TOKEN=86370cfc1685b1550e463f54db82d7785aba4b3582cf9748383de73c2c2a97d8
before_install: npm install -g grunt-cli istanbul codeclimate-test-reporter
install: npm install
before_script: grunt
script: "npm test"
after_success:
  - "npm run-script test-cov"
  - "codeclimate < ./coverage/lcov.info"
