language: node_js
sudo: false
cache:
  directories:
  - node_modules
node_js:
- '0.10'
services:
- mongodb
env: CODECLIMATE_REPO_TOKEN=86370cfc1685b1550e463f54db82d7785aba4b3582cf9748383de73c2c2a97d8
after_success: npm run codeclimate
