language: node_js
node_js:
  - "0.10.33"
services:
  - mongodb
before_install: npm install -g grunt-cli istanbul
install: npm install
before_script: grunt
script: "npm test"
after_success: "npm run-script test-cov"
